export default {
  groups: '/admin/groups',
  groupsReorder: '/admin/groups/reorder',
  users: '/admin/users',
  templates: '/admin/templates',
  projects: '/admin/projects',
  servers: '/servers',
  serversReorder: '/servers/reorder',
  variables: '/variables',
  shared: '/shared-files',
  config: '/config-files',
  notifications: '/notifications',
  heartbeats: '/heartbeats',
  urls: '/check-urls',
};
