export default {
  groups: '/admin/groups',
  groupsReorder: '/admin/groups/reorder',
  users: '/admin/users',
  templates: '/admin/templates',
  projects: '/admin/projects',
  servers: '/servers',
  serversReorder: '/servers/reorder',
  serversAutocomplete: '/servers/autocomplete',
  commands: '/commands',
  commandsReorder: '/commands/reorder',
  variables: '/variables',
  shared: '/shared-files',
  config: '/config-files',
  notifications: '/notifications',
  heartbeats: '/heartbeats',
  urls: '/check-urls',
  profileEmail: '/profile/email',
  profileImage: '/profile/avatar',
  profileGravatar: '/profile/gravatar',
  profileUpload: '/profile/upload',
};
